name: Fix Terraform file formatting

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check Terraform file are formatted correctly
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: terraform fmt
      uses: dflook/terraform-fmt@v1

    - name: setup git config
      run: |
        # set user.name 'TF Format', leave user.email empty
        git config user.name "TF Format"
        git config user.email "<>"

    - name: commit changed files into repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        commit_message: terraform fmt
